theme: minima
title: Mooliki's Digital Emporium
author: Mooliki
email: captain_hoofbucket@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
This is an awesome description for my site. It perfectly represents the marvels that this site contains. Wonders and mysterious are found within.

# social links
twitter_username: barryquinnart # DO NOT include the @ character, or else the build will fail!
github_username:  mooliki # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
